export const data = [
  {
    id: 1,
    name: "Asley ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 2,
    name: "Alex ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 3,
    name: "John ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 4,
    name: "Brad ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 5,
    name: "brander ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 6,
    name: "Asep ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 7,
    name: "Ucok ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 8,
    name: "kelvin ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 9,
    name: "david ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 10,
    name: "James ",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
];
