export const data = [
  {
    id: 1,
    name: "lorem 1",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 2,
    name: "lorem 2",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 3,
    name: "lorem 3",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 4,
    name: "lorem 4",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 5,
    name: "lorem 5",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 6,
    name: "lorem 6",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 7,
    name: "lorem 7",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 8,
    name: "lorem 8",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 9,
    name: "lorem  9",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
  {
    id: 10,
    name: "lorem 10",
    location: "USA",
    value: "lorem ipsum",
    description: "lorem ipsum dolor sit amet acumalakahahaah",
  },
];
